from datetime import date, datetime
from decimal import Decimal
from typing import Protocol

from app.modules.chama.domain.entities import ChamaContribution, ChamaGroup, ChamaMember, ChamaPayout


class ChamaGroupRepository(Protocol):
    async def create(self, *, group_name: str, contribution_cycle: str, cycle_amount: Decimal) -> ChamaGroup: ...
    async def get(self, chama_id: str) -> ChamaGroup | None: ...
    async def list_for_user(self, user_id: str, limit: int, offset: int) -> tuple[list[ChamaGroup], int]: ...


class ChamaMemberRepository(Protocol):
    async def add(self, *, chama_id: str, user_id: str, member_role: str) -> ChamaMember: ...
    async def get(self, member_id: str) -> ChamaMember | None: ...
    async def get_for_user(self, chama_id: str, user_id: str) -> ChamaMember | None: ...
    async def list_for_chama(self, chama_id: str, limit: int, offset: int) -> tuple[list[ChamaMember], int]: ...
    async def list_for_user(self, user_id: str) -> list[ChamaMember]:
        """Unpaginated: only used internally to aggregate scoring features
        across a user's memberships, never returned directly from an API
        list endpoint."""
        ...


class ChamaContributionRepository(Protocol):
    async def record(
        self, *, chama_id: str, member_id: str, cycle_due_date: date, amount_due: Decimal, amount_paid: Decimal, paid_at: datetime, is_on_time: bool
    ) -> ChamaContribution: ...
    async def punctuality(self, member_id: str) -> float:
        """On-time contributions / total contributions, as a 0-100 percentage."""
        ...
    async def list_for_member(self, member_id: str, limit: int, offset: int) -> tuple[list[ChamaContribution], int]: ...


class ChamaPayoutRepository(Protocol):
    async def schedule(self, *, chama_id: str, recipient_member_id: str, payout_amount: Decimal, scheduled_date: date) -> ChamaPayout: ...
    async def list_for_chama(self, chama_id: str, limit: int, offset: int) -> tuple[list[ChamaPayout], int]: ...
