from datetime import datetime
from typing import Protocol

from app.modules.identity.domain.entities import User


class UserRepository(Protocol):
    async def get_by_phone(self, phone_number: str) -> User | None: ...
    async def get_by_id(self, user_id: str) -> User | None: ...
    async def create(self, *, phone_number: str, full_name: str, role: str) -> User: ...


class OtpChallengeRepository(Protocol):
    async def count_recent_requests(self, phone_number: str, since: datetime) -> int: ...
    async def create(self, *, phone_number: str, code_hash: str, max_attempts: int, expires_at: datetime) -> str: ...
    async def get_active(self, phone_number: str) -> dict | None: ...
    async def increment_attempt(self, challenge_id: str) -> None: ...
    async def mark_consumed(self, challenge_id: str) -> None: ...


class RefreshTokenRepository(Protocol):
    async def create(self, *, user_id: str, token_hash: str, expires_at: datetime) -> str: ...
    async def get_by_hash(self, token_hash: str) -> dict | None: ...
    async def mark_replaced(self, token_id: str, replaced_by: str) -> None: ...
    async def revoke(self, token_id: str) -> None: ...
    async def revoke_family(self, token_id: str) -> None:
        """Walk `replaced_by` links in both directions and revoke every token
        descended from (or ancestor of) `token_id` -- used on reuse detection."""
        ...
