from datetime import datetime
from typing import Protocol

from app.modules.identity.domain.entities import User


class UserRepository(Protocol):
    async def get_by_phone(self, phone_number: str) -> User | None:
        """Active users only (deleted_at IS NULL) -- used by the OTP login path."""
        ...
    async def get_by_phone_any_status(self, phone_number: str) -> User | None:
        """Includes deactivated users -- lets the login flow distinguish
        "not registered" from "registered but deactivated" instead of
        treating a deactivated user as brand-new and re-prompting them to
        sign up again."""
        ...
    async def get_by_id(self, user_id: str) -> User | None:
        """Active users only -- used by request-time auth (a deactivated
        user's token must not resolve to a usable account)."""
        ...
    async def get_by_id_any_status(self, user_id: str) -> User | None:
        """Includes deactivated users -- used by admin management actions,
        which need to operate on (and re-activate) inactive accounts."""
        ...
    async def create(self, *, phone_number: str, full_name: str, role: str, created_by: str | None = None) -> User: ...
    async def list_all(
        self, *, limit: int, offset: int, role: str | None = None, include_inactive: bool = False
    ) -> tuple[list[User], int]: ...
    async def update(self, user_id: str, *, full_name: str | None = None, role: str | None = None) -> User: ...
    async def deactivate(self, user_id: str) -> None: ...
    async def reactivate(self, user_id: str) -> None: ...
    async def get_full_names_by_ids(self, user_ids: list[str]) -> dict[str, str]:
        """Batch name lookup (any status) for enriching audit-log rows with
        a human-readable actor/target instead of a bare UUID."""
        ...


class OtpChallengeRepository(Protocol):
    async def count_recent_requests(self, phone_number: str, since: datetime) -> int: ...
    async def create(self, *, phone_number: str, code_hash: str, max_attempts: int, expires_at: datetime) -> str: ...
    async def get_active(self, phone_number: str) -> dict | None: ...
    async def increment_attempt(self, challenge_id: str) -> None: ...
    async def mark_consumed(self, challenge_id: str) -> None: ...


class RefreshTokenRepository(Protocol):
    async def create(self, *, user_id: str, token_hash: str, expires_at: datetime) -> str: ...
    async def get_by_hash(self, token_hash: str) -> dict | None: ...
    async def mark_replaced(self, token_id: str, replaced_by: str) -> None: ...
    async def revoke(self, token_id: str) -> None: ...
    async def revoke_all_for_user(self, user_id: str) -> None: ...
    async def revoke_family(self, token_id: str) -> None:
        """Walk `replaced_by` links in both directions and revoke every token
        descended from (or ancestor of) `token_id` -- used on reuse detection."""
        ...
